snowflake_demo_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID') }}"
      client_session_keep_alive: false
      threads: 8
      database: development_cberger
      role: transformer
      schema: dbt_checkpoint
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      warehouse: transforming