# This action will trigger an already created job on dbt Cloud
# If you're trying to set this up for a **Deployment** self-deferral, you'll
# need to set up some things in your dbt Cloud job:
# 1. Choose to defer and use `Self`. This will always refer to the most recent run's manifest.
# 2. Make sure you're using the state selector. 
#    Example 1: dbt build -s state:modified+ 
#               will run changed models and anything downstream
#    Example 2: dbt build -s state:modified+1 
#               will run changed models and direct descendants
#    Example 3: dbt build -s state:modified+1 config.materialized:table 
#               Example 2 and any tables 
#               (to ensure the underlying data is refreshed with the run, even if they aren't modified)
#    Example 4: dbt build -s state:modified+1 state:new config.materialized:table
#               Examples 2 and 3 plus any new models and tests
# In development, folks will be able to use the defer command to test changes against the manifest
# added in lines 46-62.

name: Run Job on Merge
on:
  push:
    branches:
      - main_run_on_merge
  
jobs:
  run_on_merge:
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_API_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
      JOB_ID: 309178

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Run Merge Job
        run: |
          pip install dbtc==0.6.0
          run=$(dbtc trigger-job \
              --job-id=$JOB_ID \
              --payload='{"cause": "Triggered by a merge to main"}')
          echo "RUN_ID=$(echo $run | jq '.data.id')" >> $GITHUB_ENV
      
      - name: Get manifest
        id: manifest
        run: |
          manifest=$(dbtc get-run-artifact \
            --account-id=$DBT_CLOUD_ACCOUNT_ID \
            --run-id=$RUN_ID \
            --path=manifest.json)
          echo $manifest > .dbt/prod/manifest.json

      - name: Add Manifest to Repo
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.json'
          committer_name: Github Actions
          committer_email: actions@github.com
          message: 'Adding manifest from merge run'
